name: Run

# on:
#   workflow_dispatch:
#   repository_dispatch:
on: 
  schedule:
    - cron: '30 17 * * *' # UTC+8小时=北京时间 17代表凌晨一点
  watch:
    types: [started]
jobs:
  build:

    # if: github.actor == github.repository_owner
    if: github.event.repository.owner.id == github.event.sender.id || github.event_name == 'schedule'
    runs-on: ubuntu-latest

    steps:
    - name: Get log
      uses: actions/checkout@master
    # - uses: actions/checkout@main
    - name: Run
      uses: coactions/setup-xvfb@main
      with:
        # run: dotnet run
        run: curl www.baidu.com
      env: 
        CONF: ${{ secrets.CONF }}
        
    - name: Push log #更新日志
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: auto-checkin
        branch: main
